# Generated by Django 3.2.12 on 2022-04-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_bookmark_like_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
