# Generated by Django 3.2.12 on 2022-04-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_feed_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='user_id',
        ),
    ]
